config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users do
      member do
        patch :unsubscribe
      end
    end
    resources :posts
    resources :comments
  end

  scope module: :public do
    get "search" => "posts#search"
    resources :users do
      member do
        get :favorites
      end
    end

    resources :posts do
       resource :favorites, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    end

  end

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :post_jobs, dependent: :destroy
  has_many :jobs, through: :post_jobs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.search(keyword)
    where("title LIKE ?", "%#{keyword}%")
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
  end

  def destroy
     post = Post.find(params[:id]).destroy
    # post.destroy
     redirect_to admin_user_path(post.user)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/show.html.erb
<div class="container">
  <h3 class="text-center my-5">投稿詳細</h3>
    <div class="text-form-center">
      <p><%= @user.name %></p>
      <p><%= @user.age %>歳</p>
      <p><%= @user.gender %>性</p>
      <p>
        <ul>
          <% @post.jobs.each do |job| %>
            <li><%= job.job_name %></li>
          <% end %>
        </ul>
      </p>
      <p><%= @post.title %></p>
      <p><%= @post.text %></p>
      <P>いいね<%= @post.favorites.count %></P>

      <h2>コメント内容</h2>
        <% @comments.each do |comment| %>
          <%= comment.comment %>
          <%= link_to "コメント削除", admin_comment_path(comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
        <% end %>
    </div>
      <%= link_to "<<戻る", admin_user_path(@user) %>
</div>