config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users do
      member do
        patch :unsubscribe
      end
    end
    resources :posts
    resources :comments
  end

  scope module: :public do
    get "search" => "posts#search"
    resources :users do
      member do
        get :favorites
      end
    end

    resources :posts do
       resource :favorites, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    end

  end

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :favorites, dependent: :destroy

         has_one_attached :profile_image
         
    def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def unsubscribe
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_users_path
  end

 private
  def user_params
    params.require(:user).permit(:name, :gender, :age, :email, :profile_image,)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
  <h3 class="text-center my-5">ユーザー一覧</h3>
    <table class="table">
      <tr>
        <th>名前</th>
        <th>メールアドレス</th>
        <th></th>
      </tr>

        <% @users.each do |user| %>
          <tr>
            <td><%=link_to user.name,admin_user_path(user) %></td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted==false %>
                <%= link_to "退会する", unsubscribe_admin_user_path(user), method: :patch, "data-confirm" => "本当に退会しますか？" %>
              <% else %>
                <P>退会済み</P>
              <% end %>
            </td>
          </tr>
        <% end %>
    </table>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h3 class="text-center my-5"><%= @user.name %>の投稿一覧</h3>
    <table class="table">
      <tr>
        <td>職業</td>
        <td>タイトル</td>
        <td>投稿日時</td>
        <td></td>
        <td></td>
      </tr>

      <% @posts.each do |post| %>
        <tr>
          <td>
            <ul class="m-0">
              <% post.jobs.each do |job| %>
                <li><%= job.job_name %></li>
              <% end %>
            </ul>
          </td>
          <td><%= post.title %></td>
          <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
          <td>
            <%= link_to "詳細", admin_post_path(post) %>
            <%= link_to "削除", admin_post_path(post), method: :delete, data: {confirm: '削除しても良いですか？'} %>
          </td>
        </tr>
      <% end %>
    </table>
  <%= link_to "<<戻る", admin_users_path %>
</div>