config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users do
      member do
        patch :unsubscribe
      end
    end
    resources :posts
    resources :comments
  end

  scope module: :public do
    get "search" => "posts#search"
    resources :users do
      member do
        get :favorites
      end
    end

    resources :posts do
       resource :favorites, only: [:create, :destroy]
       resources :comments, only: [:create, :destroy]
    end

  end

  root to: 'homes#top'
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
    belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :user
   belongs_to :post
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :post_jobs, dependent: :destroy
  has_many :posts, through: :post_jobs, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  has_many :post_jobs, dependent: :destroy
  has_many :jobs, through: :post_jobs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.search(keyword)
    where("title LIKE ?", "%#{keyword}%")
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/post_job.rb
class PostJob < ApplicationRecord
  belongs_to :post
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :favorites, dependent: :destroy

         has_one_attached :profile_image
         
    def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def destroy
    comment = Comment.find(params[:id]).destroy
    # comment.destroy
    redirect_to admin_post_path(comment.post)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
  end

  def destroy
     post = Post.find(params[:id]).destroy
    # post.destroy
     redirect_to admin_user_path(post.user)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
    admin_users_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def unsubscribe
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_users_path
  end

 private
  def user_params
    params.require(:user).permit(:name, :gender, :age, :email, :profile_image,)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    current_user
   end

   def after_sign_out_path_for(resource)
    case resource
    when :admin 
      new_admin_session_path
    when :user  
      root_path
    end
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age, :email, :encrypted_password,])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.gender = " "
      user.age = " "
  end
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STUTTER CHOICE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/add48f0df5.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand logo" href="#">STUTTER CHOICE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <% if request.url.include?('/admin/') %><%# URLにadminが含まれている%>
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Users", admin_users_path, class: "nav-link text-dark" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "login", admin_users_path, class: "nav-link text-dark" %>
                </li>
              <% end %>
            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", user_path(current_user), class: "nav-link text-dark" %>
              </li>
               <li class="nav-item">
                <%= link_to "投稿", new_post_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link text-dark" %>
              </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "signup", new_user_registration_path, class: "nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link text-dark" %>
              </li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <% if flash[:notice] %>
    <div><%= flash[:notice] %></div>
  <% end %>
    <%= yield %>
  </body>

</html>